/*
 * Generated by the zrpc compiler (rpcc).  DO NOT EDIT!
 * @(#)$Id: traffic_signals.pro
 */

syntax = "proto3";

package traffic_signals_pbf;

message movement
{
	int32 type = 1;
	int32 status = 2;
	int32 left_time = 3;
}

message movement_array
{
	repeated movement array = 1;
}

message intersection_info
{
	string approach_id = 1;
	int64 timestamp = 2;
	bool in_intersection = 3;
	int32 status = 4;
	int32 movement_count = 5;
	repeated movement items = 6;
}

message intersection_info_array
{
	repeated intersection_info array = 1;
}

message gps_info
{
	double latitude = 1;
	double longitude = 2;
	double direction = 3;
}

message gps_info_array
{
	repeated gps_info array = 1;
}

message vehicle_info
{
	string veh_id = 1;
	double veh_speed = 2;
	int64 timestamp = 3;
	gps_info gps = 4;
}

message vehicle_info_array
{
	repeated vehicle_info array = 1;
}

message ___vehilce_dt_update_vehicle_info_inparam
{
	vehicle_info info = 1;
}

message ___vehilce_dt_update_vehicle_info_inout_param
{
	int32 ___retval = 1;
}

message ___traffic_signal_listener_on_traffic_light_changed_inparam
{
	intersection_info int_info = 1;
}

message ___traffic_signal_info_get_current_inout_param
{
	intersection_info ___retval = 1;
}

message ___traffic_signal_info_register_traffic_signal_listener_inparam
{
	int64 lnr = 1;
	string client_name_lnr = 2;
	string inst_name_lnr = 3;
}

message ___traffic_signal_info_register_traffic_signal_listener_inout_param
{
	int32 ___retval = 1;
}

message ___traffic_signal_info_deregister_traffic_signal_listener_inparam
{
	int64 lnr = 1;
	string client_name_lnr = 2;
	string inst_name_lnr = 3;
}

message ___traffic_signal_info_deregister_traffic_signal_listener_inout_param
{
	int32 ___retval = 1;
}

message ___traffic_signal_mgr_register_vehicle_inparam
{
	vehicle_info info = 1;
}

message ___traffic_signal_mgr_register_vehicle_inout_param
{
	int64 ___retval = 1;
}

message ___traffic_signal_mgr_get_traffic_signal_inparam
{
	vehicle_info info = 1;
}

message ___traffic_signal_mgr_get_traffic_signal_inout_param
{
	int64 ___retval = 1;
}

