if (NOT PROTO_FILE_ROOT_PATH)
	set(PROTO_FILE_ROOT_PATH  ${PROJECT_SOURCE_DIR})
endif()
if (NOT PROTO_TARGET_NAME)
	set(PROTO_TARGET_NAME  ${PROJECT_NAME}_proto_target)
endif()

find_package(Protobuf REQUIRED)
set(INNER_PROTO_INTERFACE_DIR ${PROTO_FILE_ROOT_PATH}/proto)
# set(INNER_PROTO_TARGET_NAME ${PROJECT_SOURCE_DIR}/_proto_target)
set(INNER_PROTO_TARGET_NAME ${PROTO_TARGET_NAME})

