/** @file utils.h
 */

#ifndef __CXX_ZAS_UTILS_H__
#define __CXX_ZAS_UTILS_H__

#include "std/zasbsc.h"

#ifdef LIBUTILS
#define UTILS_EXPORT		__attribute__((visibility("default")))
#else
#define UTILS_EXPORT
#endif

#ifndef UTILS_FBLOCK_CONFIG
// enable all function blocks

#define UTILS_ENABLE_FBLOCK_ABSFILE
#define UTILS_ENABLE_FBLOCK_BUFFER
#define UTILS_ENABLE_FBLOCK_CERT
#define UTILS_ENABLE_FBLOCK_CMDLINE
#define UTILS_ENABLE_FBLOCK_COROUTINE
#define UTILS_ENABLE_FBLOCK_DATAPOOL
#define UTILS_ENABLE_FBLOCK_DIR
#define UTILS_ENABLE_FBLOCK_EVENTLOOP
#define UTILS_ENABLE_FBLOCK_EVLCLIENT
#define UTILS_ENABLE_FBLOCK_EVLOOP
#define UTILS_ENABLE_FBLOCK_LOG
#define UTILS_ENABLE_FBLOCK_MEMCACHE
#define UTILS_ENABLE_FBLOCK_SHRMEM
#define UTILS_ENABLE_FBLOCK_SYSCFG
#define UTILS_ENABLE_FBLOCK_THREAD
#define UTILS_ENABLE_FBLOCK_TIMER
#define UTILS_ENABLE_FBLOCK_URI
#define UTILS_ENABLE_FBLOCK_EXPRVM
#define UTILS_ENABLE_FBLOCK_UUID
#define UTILS_ENABLE_FBLOCK_WAIT

#else
#include UTILS_FBLOCK_ENABLE_LIST
#endif

#endif /* __CXX_ZAS_UTILS_H__ */
/* EOF */
