/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_civip_hdmap_jni_JNIHDMapRender */

#ifndef _Included_com_civip_hdmap_jni_JNIHDMapRender
#define _Included_com_civip_hdmap_jni_JNIHDMapRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    createNativeMapRender
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_createNativeMapRender
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    getBlockDepends
 * Signature: (J[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_getBlockDepends
  (JNIEnv *, jobject, jlong, jintArray);

/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    getHDMapInfo
 * Signature: (J[I[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_getHDMapInfo
  (JNIEnv *, jobject, jlong, jintArray, jintArray);

/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    getMapHeadInfo
 * Signature: (J)Lcom/civip/hdmap/jni/MapHead;
 */
JNIEXPORT jobject JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_getMapHeadInfo
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    getMapSingleLight
 * Signature: (J)[Lcom/civip/hdmap/jni/SingleLight;
 */
JNIEXPORT jobjectArray JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_getMapSingleLight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    getHDMapJunction
 * Signature: (JLjava/lang/String;)[Lcom/civip/hdmap/jni/Junction;
 */
JNIEXPORT jobjectArray JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_getHDMapJunction
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_civip_hdmap_jni_JNIHDMapRender
 * Method:    getJunctionByPos
 * Signature: (JLjava/lang/String;DDI)Lcom/civip/hdmap/jni/Junction;
 */
JNIEXPORT jobject JNICALL Java_com_civip_hdmap_jni_JNIHDMapRender_getJunctionByPos
  (JNIEnv *, jobject, jlong, jstring, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
